### ISSUE TITLE
Jbox官网发送消息功能页面上一个提示信息有错

### ISSUE THREAD

**Issue by slate6** [jpush/jbox#1]
首先谢谢你们开发了这么牛，这么好用的工具，实在是太方便了，用于服务器监控或群发量不大的业务消息很给你。
在官网登陆后，发消息页面，如果有错误的话会提示

> “发送失败，可能还**有**有设备订阅该频道”

我想那应该是“还**没**有”吧。JS里面有两处都是这么写的。

**Comment by huangminlinux** [comment]
这个错误提示， 意思是手机app 没有扫描这个频道的二维码。

一个频道最少要有一个设备扫码订阅后才能推送具体的消息， 不然服务器不知道要推送到哪些设备。

**Comment by slate6** [comment]
好的，谢谢解释。

**Comment by huangminlinux** [comment]
使用过程中遇到问题也可以在 Q群中交流，QQ群：453471823
