### ISSUE TITLE
请问官网二级域名下的jbox能不能用？

### ISSUE THREAD

**Issue by ilaotan** [jpush/jbox#2]
如题，我试用 (https://jbox.jiguang.cn/auth/send_message)   的服务及api接口，都返回错误

>  { "error": "JPush failed, please read the code and refer code document" }

如果我要尝试使用，非得自搭python版的server端？

**Comment by huangminlinux** [comment]
如果是直接使用，不需要要管这个接口吧，  直接使用这个接口就可以了 https://jbox.jiguang.cn/document

建议先看使用教程 https://jbox.jiguang.cn/guide。

**Comment by ilaotan** [comment]
@huangminlinux  您看我有需要注意的东西没填吗？ Header里只加Accept=application/json 提示400

> The browser (or proxy) sent a request that this server could not understand.

加上Content-Type后 就跟页面版返回的错误信息一样了（也就是我1楼贴的那个）
![001](https://user-images.githubusercontent.com/6210438/27813038-a80d41ba-60a5-11e7-9843-3bf5fa69902d.png)
![002](https://user-images.githubusercontent.com/6210438/27813040-addd8f5a-60a5-11e7-99ad-4e5c90824cda.png)

**Comment by huangminlinux** [comment]
手机App 有扫码订阅没？

**Comment by ilaotan** [comment]
@huangminlinux  扫了，已经订阅了。

**Comment by huangminlinux** [comment]
![wechatimg85](https://user-images.githubusercontent.com/5852088/27814310-2bdce780-6041-11e7-80b5-3a8e039267c0.jpeg)

进入编辑 Channel 的页面重新点选试试，我猜可能是没有订阅成功

**Comment by huangminlinux** [comment]
接口使用没有问题

**Comment by ilaotan** [comment]
@huangminlinux  我只建了一个chanel，各种测不通，然后今天我又建了个channel。 然后这俩channel都好用了。。。。。
